---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "false"
  name: wss-k8s
  labels:
    app: wss-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wss-k8s
  template:
    metadata:
      labels:
        app: wss-k8s
    spec:
      containers:
      - name: wss-k8s
        image: yllam/wss-k8s:1.0.0
        env:
        - name: K8S_POD_NAME
          valueFrom: {fieldRef: {fieldPath: metadata.name}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred

