apiVersion: v1
kind: Service
metadata:
  name: wss-k8s
  labels:
    app: wss-k8s
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: wss-k8s